import { describe, it } from "node:test";
import assert from "node:assert/strict";
import { createPatch } from "diff";
import { applyDiff } from "../src/patch.ts";

describe("applyDiff — happy path", () => {
	it("applies a single hunk generated by createPatch (round-trip)", () => {
		const old = "line1\nline2\nline3\nline4\nline5\n";
		const next = "line1\nline2\nCHANGED\nline4\nline5\n";
		const diff = createPatch("file.txt", old, next);

		const out = applyDiff(old, diff);

		assert.equal(out.applied, true);
		assert.equal(out.content, next);
		assert.equal(out.hunks.length, 1);
		assert.equal(out.error, undefined);
	});

	it("applies multiple hunks to one file and reports each", () => {
		const old = "a\nb\nc\nd\ne\nf\ng\nh\n";
		const next = "A\nb\nc\nd\ne\nf\ng\nH\n";
		const diff = createPatch("file.txt", old, next, undefined, undefined, { context: 1 });

		const out = applyDiff(old, diff);

		assert.equal(out.applied, true);
		assert.equal(out.content, next);
		assert.equal(out.hunks.length, 2);
	});

	it("applies a headerless diff (just @@ hunks)", () => {
		const source = "a\nb\nc\n";
		const diff = "@@ -1,3 +1,3 @@\n a\n-b\n+B\n c\n";

		const out = applyDiff(source, diff);

		assert.equal(out.applied, true);
		assert.equal(out.content, "a\nB\nc\n");
	});

	it("ignores file headers — path is authoritative", () => {
		const source = "a\nb\nc\n";
		const diff = "--- a/whatever.txt\n+++ b/whatever.txt\n@@ -1,3 +1,3 @@\n a\n-b\n+B\n c\n";

		const out = applyDiff(source, diff);

		assert.equal(out.applied, true);
		assert.equal(out.content, "a\nB\nc\n");
	});
});

describe("applyDiff — hunk section headers (text after the closing @@)", () => {
	// Real `git diff` output and most LLM-emitted diffs carry a section header
	// after the second `@@` (e.g. `@@ -10,7 +10,7 @@ class Foo {`). `parsePatch`
	// splits on `@@ -N,N +N,N @@` and ignores the trailing text, so these apply.
	// This block pins that behavior and documents it.

	it("applies a single hunk with a trailing class header", () => {
		const source = "class Foo {\n  a() {}\n  b() {}\n}\n";
		const diff = "@@ -1,4 +1,4 @@ class Foo {\n class Foo {\n   a() {}\n-  b() {}\n+  B() {}\n }\n";

		const out = applyDiff(source, diff);

		assert.equal(out.applied, true);
		assert.equal(out.content, "class Foo {\n  a() {}\n  B() {}\n}\n");
	});

	it("applies a single hunk with a trailing function header", () => {
		const source = "export function bar() {\n  return 1;\n}\n";
		const diff = "@@ -1,3 +1,3 @@ export function bar() {\n export function bar() {\n-  return 1;\n+  return 2;\n }\n";

		const out = applyDiff(source, diff);

		assert.equal(out.applied, true);
		assert.equal(out.content, "export function bar() {\n  return 2;\n}\n");
	});

	it("applies multi-hunk diffs where each hunk carries a different section header", () => {
		const source = [
			"class Foo {",
			"  a() {",
			"    return 1;",
			"  }",
			"  b() {",
			"    return 2;",
			"  }",
			"}",
			"",
		].join("\n");
		const diff = [
			"@@ -1,4 +1,4 @@ class Foo {",
			" class Foo {",
			"   a() {",
			"-    return 1;",
			"+    return 10;",
			"   }",
			"@@ -5,4 +5,4 @@   b() {",
			"   b() {",
			"-    return 2;",
			"+    return 20;",
			"   }",
			" }",
		].join("\n");

		const out = applyDiff(source, diff);

		assert.equal(out.applied, true);
		assert.equal(out.hunks.length, 2);
		assert.equal(
			out.content,
			[
				"class Foo {",
				"  a() {",
				"    return 10;",
				"  }",
				"  b() {",
				"    return 20;",
				"  }",
				"}",
				"",
			].join("\n"),
		);
	});

	it("rejects when the section header names a symbol not present in the file (assume wrong file)", () => {
		// The header says `function wrongName()` but the file has `class Foo`. Under
		// the caption-guided design, a caption that doesn't appear in the file means
		// the agent likely has the wrong file (or a stale snapshot) — not the wrong
		// symbol. Reject rather than apply somewhere the agent didn't name.
		const source = "class Foo {\n  a() {}\n}\n";
		const diff = "@@ -1,3 +1,3 @@ function wrongName() {\n class Foo {\n-  a() {}\n+  A() {}\n }\n";

		const out = applyDiff(source, diff);

		assert.equal(out.applied, false);
		assert.equal(out.content, undefined);
		assert.match(out.error ?? "", /Section header not found/);
		assert.match(out.error ?? "", /wrongName/);
	});

	it("round-trips a createPatch diff that includes section headers", () => {
		// `createPatch` does NOT emit trailing section headers itself, but the format
		// we accept does. Confirm a hand-added header on a createPatch body still applies.
		const old = "function f() {\n  return 1;\n}\n";
		const next = "function f() {\n  return 2;\n}\n";
		const generated = createPatch("f.ts", old, next);
		// Splice a section header onto the @@ line.
		const withHeader = generated.replace(
			"@@ -1,3 +1,3 @@\n",
			"@@ -1,3 +1,3 @@ function f() {\n",
		);

		const out = applyDiff(old, withHeader);

		assert.equal(out.applied, true);
		assert.equal(out.content, next);
	});

	it("caption does NOT override a plausible oldStart: header names Foo but oldStart points at Bar → applies at Bar", () => {
		// Policy: respect the line number. `oldStart=6` points at Bar and is
		// plausible (≥ the `class Foo:` anchor at line 1), so we trust it — the
		// caption is not used to override a plausible line number. Foo/Bar with a
		// mismatched caption + plausible oldStart is not rescuable without
		// discarding line numbers, which we don't do. The caption still validates
		// (it exists in the file, so no reject) but does not steer.
		const source = [
			"class Foo:",
			"    def __init__(self):",
			"        self.x = 1",
			"",
			"class Bar:",
			"    def __init__(self):",
			"        self.x = 1",
			"",
		].join("\n");
		const captionFooOldStartAtBar = [
			"@@ -6,3 +6,3 @@ class Foo:",
			"     def __init__(self):",
			"-        self.x = 1",
			"+        self.x = 99",
			" ",
		].join("\n");

		const out = applyDiff(source, captionFooOldStartAtBar);

		assert.equal(out.applied, true);
		assert.equal(out.content, [
			"class Foo:",
			"    def __init__(self):",
			"        self.x = 1",
			"",
			"class Bar:",
			"    def __init__(self):",
			"        self.x = 99",
			"",
		].join("\n"), "plausible oldStart is respected; caption does not steer");
	});

	it("caption corrects oldStart when it points BEFORE the anchor (nonsensical) → re-derives into the named scope", () => {
		// `oldStart=1` points at `class Foo:` (line 1), but the caption says
		// `class Bar:` (anchor at line 5). A hunk cannot be inside `class Bar:` if
		// its oldStart is above `class Bar:` — that's nonsensical, so we correct
		// oldStart to the first context line at/after the anchor (Bar's
		// `def __init__` at line 6) and apply there. This is the one case where the
		// caption actively changes the outcome.
		const source = [
			"class Foo:",
			"    def __init__(self):",
			"        self.x = 1",
			"",
			"class Bar:",
			"    def __init__(self):",
			"        self.x = 1",
			"",
		].join("\n");
		const captionBarOldStartBeforeAnchor = [
			"@@ -1,3 +1,3 @@ class Bar:",
			"     def __init__(self):",
			"-        self.x = 1",
			"+        self.x = 99",
			" ",
		].join("\n");

		const out = applyDiff(source, captionBarOldStartBeforeAnchor);

		assert.equal(out.applied, true);
		assert.equal(out.content, [
			"class Foo:",
			"    def __init__(self):",
			"        self.x = 1",
			"",
			"class Bar:",
			"    def __init__(self):",
			"        self.x = 99",
			"",
		].join("\n"), "oldStart before anchor is re-derived to the named scope (Bar)");
	});

	it("without a caption, non-unique context resolves to oldStart's nearest match", () => {
		// Same source as above, but NO caption. oldStart=6 points at Bar, and the
		// context lines match Bar first → Bar is edited. This demonstrates the
		// ambiguity that the caption is meant to resolve: the agent has no way to
		// say "I meant Foo" without either a caption or a unique context line.
		const source = [
			"class Foo:",
			"    def __init__(self):",
			"        self.x = 1",
			"",
			"class Bar:",
			"    def __init__(self):",
			"        self.x = 1",
			"",
		].join("\n");
		const noCaptionOldStartAtBar = [
			"@@ -6,3 +6,3 @@",
			"     def __init__(self):",
			"-        self.x = 1",
			"+        self.x = 99",
			" ",
		].join("\n");

		const out = applyDiff(source, noCaptionOldStartAtBar);

		assert.equal(out.applied, true);
		assert.equal(out.content, [
			"class Foo:",
			"    def __init__(self):",
			"        self.x = 1",
			"",
			"class Bar:",
			"    def __init__(self):",
			"        self.x = 99",
			"",
		].join("\n"), "without a caption the scan lands at oldStart's nearest match (Bar)");
	});

	it("caption + plausible oldStart at the caption's own scope: applies at oldStart (no correction needed)", () => {
		// Caption says `class Bar:` (anchor line 5), oldStart=6 points at Bar's
		// `def __init__`. oldStart ≥ anchor, so it's kept. The context also appears
		// in Foo (before the caption), but oldStart points at Bar and the library's
		// forward-first scan from oldStart matches Bar immediately — it does not
		// scan back to Foo. This pins that a plausible oldStart wins even when an
		// earlier duplicate of the context exists.
		const source = [
			"class Foo:",
			"    def __init__(self):",
			"        self.x = 1",
			"",
			"class Bar:",
			"    def __init__(self):",
			"        self.x = 1",
			"",
		].join("\n");
		const captionBar = [
			"@@ -6,3 +6,3 @@ class Bar:",
			"     def __init__(self):",
			"-        self.x = 1",
			"+        self.x = 99",
			" ",
		].join("\n");

		const out = applyDiff(source, captionBar);

		assert.equal(out.applied, true);
		assert.equal(out.content, [
			"class Foo:",
			"    def __init__(self):",
			"        self.x = 1",
			"",
			"class Bar:",
			"    def __init__(self):",
			"        self.x = 99",
			"",
		].join("\n"), "plausible oldStart at Bar applies at Bar, not at the earlier Foo duplicate");
	});
});

describe("applyDiff — fuzzy matching", () => {
	it("applies when the hunk header line number is off (scanning finds context)", () => {
		// Hunk claims oldStart=1 with context "a","b", but source has "a","b" at lines 3-4.
		const source = "x\ny\na\nb\nz\n";
		const diff = "@@ -1,2 +1,2 @@\n a\n-b\n+c\n";

		const out = applyDiff(source, diff);

		assert.equal(out.applied, true);
		assert.equal(out.content, "x\ny\na\nc\nz\n");
	});

	it("tolerates trailing-whitespace differences via the default compareLine", () => {
		const source = "a\nb   \nc\n"; // source line has trailing spaces
		const next = "a\nB\nc\n";
		const diff = createPatch("f", "a\nb\nc\n", next); // diff generated against clean "b"

		const out = applyDiff(source, diff);

		assert.equal(out.applied, true);
		assert.equal(out.content, "a\nB\nc\n");
	});

	it("fuzzFactor=1 accepts a far-context mismatch that fuzzFactor=0 rejects", () => {
		// The mismatch is in the LAST context line ("e" vs "WRONG"), not adjacent
		// to the insertion — the library requires immediate insertion context to
		// match exactly regardless of fuzzFactor, so a near mismatch would fail both.
		const source = "a\nb\nc\nd\nWRONG\n";
		const diff = "@@ -1,5 +1,5 @@\n a\n-b\n+B\n c\n d\n e\n";

		const strict = applyDiff(source, diff, { fuzzFactor: 0 });
		assert.equal(strict.applied, false);

		const fuzzy = applyDiff(source, diff, { fuzzFactor: 1 });
		assert.equal(fuzzy.applied, true);
		// With fuzz, the library treats the mismatched context as a substitution;
		// the insertion itself still lands. Don't over-assert exact bytes.
		assert.match(fuzzy.content ?? "", /^a\nB\nc\n/);
	});

	it("normalizes CRLF source against an LF diff (autoConvertLineEndings)", () => {
		const source = "a\r\nb\r\nc\r\n";
		const diff = "@@ -1,3 +1,3 @@\n a\n-b\n+B\n c\n"; // LF diff

		const out = applyDiff(source, diff);

		assert.equal(out.applied, true);
		assert.equal(out.content, "a\r\nB\r\nc\r\n");
	});
});

describe("applyDiff — rejection", () => {
	it("rejects a multi-file diff with a clear error", () => {
		const diff = createPatch("a.txt", "x\n", "y\n") + createPatch("b.txt", "x\n", "y\n");

		const out = applyDiff("x\n", diff);

		assert.equal(out.applied, false);
		assert.match(out.error ?? "", /2 file sections/);
		assert.equal(out.hunks.length, 0);
	});

	it("reports failure when a hunk's context is absent (no per-hunk diagnostics)", () => {
		const source = "a\nb\nc\n";
		const diff = "@@ -1,2 +1,2 @@\n x\n-y\n+z\n";

		const out = applyDiff(source, diff);

		assert.equal(out.applied, false);
		assert.equal(out.hunks.length, 0);
		assert.match(out.error ?? "", /Patch did not apply/);
	});

	it("treats an empty diff as a no-op (content unchanged)", () => {
		const out = applyDiff("a\nb\n", "");

		assert.equal(out.applied, true);
		assert.equal(out.content, "a\nb\n");
		assert.equal(out.hunks.length, 0);
	});

	it("surfaces a parse error for a truly malformed body (line with no op prefix)", () => {
		// Header count mismatches are normalized away (the body is authoritative),
		// but a body line that isn't ` `/`-`/`+`/`\` is a genuine structural error
		// that `parsePatch` still rejects. This pins that we didn't swallow it.
		const diff = "@@ -1,3 +1,3 @@\n a\nbogus\n-b\n+B\n c\n";
		const out = applyDiff("a\nb\nc\n", diff);

		assert.equal(out.applied, false);
		assert.match(out.error ?? "", /Failed to parse diff/);
	});
});

describe("applyDiff — line-count normalization", () => {
	// `diff`'s `parsePatch` validates the `@@ -oldLines,newLines @@` header counts
	// against the hunk body and throws on any mismatch. LLMs miscount these headers
	// frequently, but the body is authoritative (the LLM copies the actual lines).
	// We recompute the counts from the body before parsing so a miscounted header
	// never reaches the parser. This block pins that behavior.

	it("applies when oldLines is too low (header says 2, body has 3)", () => {
		const source = "a\nb\nc\n";
		const diff = "@@ -1,2 +1,3 @@\n a\n-b\n+B\n c\n"; // body: 3 old, 3 new
		const out = applyDiff(source, diff);
		assert.equal(out.applied, true);
		assert.equal(out.content, "a\nB\nc\n");
	});

	it("applies when oldLines is too high (header says 4, body has 3)", () => {
		const source = "a\nb\nc\n";
		const diff = "@@ -1,4 +1,3 @@\n a\n-b\n+B\n c\n";
		const out = applyDiff(source, diff);
		assert.equal(out.applied, true);
		assert.equal(out.content, "a\nB\nc\n");
	});

	it("applies when newLines is too low (header says 2, body has 3)", () => {
		const source = "a\nb\nc\n";
		const diff = "@@ -1,3 +1,2 @@\n a\n-b\n+B\n c\n";
		const out = applyDiff(source, diff);
		assert.equal(out.applied, true);
		assert.equal(out.content, "a\nB\nc\n");
	});

	it("applies when both counts are too low", () => {
		const source = "a\nb\nc\n";
		const diff = "@@ -1,2 +1,2 @@\n a\n-b\n+B\n c\n";
		const out = applyDiff(source, diff);
		assert.equal(out.applied, true);
		assert.equal(out.content, "a\nB\nc\n");
	});

	it("normalizes counts for a multi-hunk diff where only some headers are wrong", () => {
		const source = "a\nb\nc\nd\ne\n";
		const diff = [
			"@@ -1,2 +1,2 @@", // correct
			" a",
			"-b",
			"+B",
			"@@ -3,99 +3,99 @@", // wildly wrong counts; body is fine
			" c",
			"-d",
			"+D",
		].join("\n");
		const out = applyDiff(source, diff);
		assert.equal(out.applied, true);
		assert.equal(out.content, "a\nB\nc\nD\ne\n");
	});

	it("round-trips a createPatch diff that lacks a trailing newline (EOFNL markers)", () => {
		// The `\ No newline at end of file` marker annotates the preceding `-`/`+`
		// line and is NOT counted toward either total, but it does not terminate
		// the hunk — a `+` line can follow a `\` marker. Normalization must keep
		// counting past the marker so newLines is correct (3, not 2).
		const old = "a\nb\nc"; // no trailing newline
		const next = "a\nb\nC";
		const diff = createPatch("f", old, next);
		const out = applyDiff(old, diff);
		assert.equal(out.applied, true);
		assert.equal(out.content, next);
	});

	it("applies a pure-insertion hunk (oldLines=0)", () => {
		const source = "a\nb\nc\n";
		// Insert `d` after `c`. diff format: oldStart is one-past the anchor when
		// oldLines is 0. The header counts (0 and 1) are recomputed from the body
		// (just a `+` line), so even a wrong oldLines here would be corrected.
		const diff = "@@ -3,0 +4,1 @@\n+d\n";
		const out = applyDiff(source, diff);
		assert.equal(out.applied, true);
		assert.equal(out.content, "a\nb\nc\nd\n");
	});
});
